### PR TITLE
Removed Guava (left in tests)

### PR DESCRIPTION
**Pull request by Capstan**

### CODE REVIEW

**Comment by soberich** [comment]
@Capstan I gave the permission to you for my forks so you can (could) push directly there. I see now I exposed my emails here and there. Can we remove it so it is at most `soberich` or nothing? The one in `core-utils` is already merged (, but this one is not, at least.

**Comment by Capstan** [comment]
@soberich Used `git commit --amend --author='soberich <noreply@github.com>'`

**Comment by soberich** [comment]
@Capstan I meant not removing the fact that I committed ), so that could be reversed to `25544967+soberich@users.noreply.github.com` for instance, but IN sources itself. Look in Iterables.java.

**Comment by Capstan** [comment]
Ok, I stripped Iterables and restored the commit email.

**Pull request merged**
